# Generated by Django 5.1.7 on 2025-03-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('days', models.JSONField()),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('room_type', models.CharField(max_length=50)),
            ],
        ),
    ]
